### ISSUE TITLE
Diff is selecting stack trace

### ISSUE THREAD

**Issue by kayneb** [mradionov/karma-jasmine-diff-reporter#10]
As can be seen in this screenshot:

<img width="1418" alt="screen shot 2016-02-01 at 4 15 31 pm" src="https://cloud.githubusercontent.com/assets/4030649/12731458/13f60b0e-c8ff-11e5-9c88-12f0716e3c27.png">

The diff reporter is selecting stack the trace. This is when using karma 0.12.37 and PhantomJS 2.1.1.

**Comment by kayneb** [comment]
Seems like either karma 0.12.37 or PhantomJS 2.1.1 doesn't print `at` anymore. How about just checking for period followed by new line instead of trying to detect the stack trace?

**Comment by mradionov** [comment]
Thanks for reporting the issue. Yeah, I am using `at` to identify where the stack trace starts. I'll take a look what I can do in order to fix it. Could you please share what reporters do you use?

**Comment by kayneb** [comment]
I'm using just progress.

I just checked, and this also happens with PhantomJS 1.9.8:

<img width="1420" alt="screen shot 2016-02-01 at 4 40 23 pm" src="https://cloud.githubusercontent.com/assets/4030649/12732211/8af0b922-c902-11e5-8b17-e30953d646f5.png">

**Comment by mradionov** [comment]
Yes, I was able to reproduce it with PhantomJS, thanks.

**Comment by mradionov** [comment]
@kayneb , I've just pushed an update to master branch, it would be really great if you could test it with your code before I publish the fix. I am gonna do a few more tests and publish it anyways. Thanks!

**Comment by kayneb** [comment]
Yep it's working with PhantomJS v2.1.1!

**Comment by kayneb** [comment]
Please do a release! Would love to have this fix :D

**Comment by mradionov** [comment]
Version [0.3.3](https://www.npmjs.com/package/karma-jasmine-diff-reporter) is now available on npm.
