### ISSUE TITLE
Spaces in strings not show in diff

### ISSUE THREAD

**Issue by ValentinH** [mradionov/karma-jasmine-diff-reporter#15]
For instance, if you do:
``` js
expect('test  test').toEqual('test test')
```

The output is:
![image](https://cloud.githubusercontent.com/assets/2678610/17018376/bf519112-4f37-11e6-9d38-f456ae2f20e5.png)

In this example, it's quite obvious but in a big diff it can get tricky...

I understand that this is not a bug but just that the extra space is actually colored but not visible.

A solution might be to replace spaces that are different by the ␣ character or by another one.

**Comment by ValentinH** [comment]
Actually, the issue is mainly due because I use to following colors config:
```js
color: {
  expectedBg: 'bgBlack',        // default 'bgRed'
  expectedFg: 'green',   // default 'white'
  actualBg: 'bgBlack',          // default 'bgGreen'
  actualFg: 'red'       // default 'white',
}
```

**Comment by mradionov** [comment]
Nice find! I think that replacing characters will bring some confusion, it's better not to modify the data. Currently my idea is to add an extra color option like `whitespaceBg`, which would allow to specify a background color for whitespaces separately. I'll see how it goes and let you know. Thanks!

**Comment by mradionov** [comment]
Update is available in [0.6.0](https://www.npmjs.com/package/karma-jasmine-diff-reporter)

Example is in [Colors](https://github.com/mradionov/karma-jasmine-diff-reporter#colors) section. Basically there are two new options:

```
color: {
  expectedWhitespaceBg: 'bgRed',  // default
  actualWhitespaceBg: 'bgGreen' // default
}
```

which allow to control a color of whitespace background independently from text color, and vice versa.

With your setup whitespaces should be highlighted out of the box when you upgrade to 0.6.0

**Comment by mradionov** [comment]
Note, that you don't have to set these options, which I've mentioned in a code sample, in your karma config - these values are by default. Use them only if you want to have another background color different from default red and green.

**Comment by ValentinH** [comment]
:+1: again thanks for being that fast! :)
