### ISSUE TITLE
Add a Function difference

### ISSUE THREAD

**Issue by MLefebvreICO** [mradionov/karma-jasmine-diff-reporter#18]
When have have two `Function` into an object that we compare, the `Function`'s are not highlighted.

We were talking a bit about it in #17.

I suggest adding a new color (by default it would be orange?) that when we compare `Function` to `Function` both would be in that color to lift up a flag that it could be different.

Also, regarding this, I would consider `jasmine.any(Function)` and `Function` the same and therefore not show any colors at all.

**Comment by mradionov** [comment]
That's a nice suggestion. I am not sure that I'll be able to match `Function` in one object to another `jasmine.any(Function)` in another object keeping the same nest level, but I'll give it a shot. Thanks!

**Comment by mradionov** [comment]
Both issues have been tackled in a new version - [1.0.0](https://github.com/mradionov/karma-jasmine-diff-reporter/releases/tag/v1.0.0):
- references and other complex cases are highlighted with warning color, the color can be configured separately using `color` option
- `jasmine.any` respects a type of the value it is compared to
