### ISSUE TITLE
Only portion of diff is displayed when `pretty` is set to true

### ISSUE THREAD

**Issue by dmnrmr** [mradionov/karma-jasmine-diff-reporter#24]
```
"karma": "1.4.1",
"karma-jasmine-diff-reporter": "1.0.0"
```

Reporter: ` reporters: ['junit', 'jasmine-diff', 'dots']`

Settings:
```
pretty: true,
multiline: true
```

Output:

![image](https://cloud.githubusercontent.com/assets/7805266/23063560/e141ba68-f513-11e6-980b-528759c8621e.png)

Settings:
```
pretty: false,
multiline: true
```

Output:

![image](https://cloud.githubusercontent.com/assets/7805266/23063581/02908654-f514-11e6-9fe1-6ba62926142f.png)

**Comment by mradionov** [comment]
Thanks, I'll look into that.

**Comment by mradionov** [comment]
Unfortunately I am unable to reproduce the issue. I've installed the same karma version, all of the reporters you've mentioned and used the same object you use in the test, but no luck. Maybe there is something else? Do you have the same issue when you only keep one reporter: `reporters: ['jasmine-diff']`? Have you noticed this behavior for only this object or any other output? I appreciate any help.
It would be great if you could either try to reduce you karma config file to the minimal state when the issue still reproducible or share your karma config so I could try to do it.

**Comment by dmnrmr** [comment]
I actually tried with only `reporters: ['jasmine-diff']` and stumbled upon same problem. However I didn't try to minimize config or try a different object. I will try some more scenarios on monday when I get back to work.

**Comment by dmnrmr** [comment]
After taking a closer look to our karma config I've found out that there's actually a function that limits stacktrace output to 10 lines.
