### ISSUE TITLE
Space in object key not displayed

### ISSUE THREAD

**Issue by lpww** [mradionov/karma-jasmine-diff-reporter#25]
Spaces in key names are not displayed in the diff report. This can result in a failing test with no diff highlighted by the reporter. Not sure if this is a bug or a configuration issue?

Recreate:

>it('should have a space in the key', () => {
        expect({ hithere: true }).toEqual({ 'hi there': true });
      });

The test will correctly fail but the reporter will print the following result:

>Expected	
	  Object({ hithere: true })
	to equal
	  Object({ hithere: true })

The reporter settings:

>jasmineDiffReporter: {
      pretty: true,
      multiline: true,
      matchers: {
        toContain: {
          pattern: /Expected ([\S\s]\*) to contain ([\S\s]\*)\\./,
          reverse: false
        }
      }
    }

Running with dots reporter:

> reporters: ['jasmine-diff', 'dots']

**Comment by mradionov** [comment]
Thank you for reporting the bug, but I am having trouble with reproducing it, it keeps the space for me. I don't have a clue what is the cause. It would be great if you could try to reduce your `karma.conf.js` to the minimum when the issue becomes reproducible and share it with me. If it does not help it might be useful to know your operating system, browser your run tests in and terminal which displays the results. Any help is appreciated, Thanks!

**Comment by mradionov** [comment]
Feel free to reopen if you have any more information.
