### ISSUE TITLE
Jasmine 2.6 released with it's own diff

### ISSUE THREAD

**Issue by mradionov** [mradionov/karma-jasmine-diff-reporter#27]
Jasmine finally got it's own version of "pretty print" for objects, which is available from version 2.6.0, and you are probably using that same version. That would be the reason why you might not have an output, which was expected from my reporter. Now it will look like this:

```
Expected object to have properties
    b: 43
Expected object not to have properties
    a: 42
    at Object.<anonymous> (spec/test.test.js:3:27)
```

Here is original issue in Jasmine rep: jasmine/jasmine#675 and respective PR jasmine/jasmine#1163.

I have to think about what to do next, because I did not expect it to happen this soon and I've just recently completed a major rewrite of the reporter. Probably I'll just keep it as is, so it will work only with Jasmine versions prior 2.6, because I have no idea how they are gonna continue improving their diff output and it might be difficult to adapt to from my side.

Thank you for your report, if you really want to use this reporter at full capacity, the only thing for now is to downgrade Jasmine to 2.5, but I am not insisting on it in any ways, because Jasmine might have things fixed and improved in latest versions.

Another option might be to introduce an option in my reporter to ignore new Jasmine 2.6 diff output and bring back old 2.5 output by monkey-patching Jasmine, what I already do anyways, but it will also allow reporter to continue working as before.

**Comment by mradionov** [comment]
New version [1.1.0](https://www.npmjs.com/package/karma-jasmine-diff-reporter) is now available on npm.

By default Jasmine 2.6 diffs will be respected and not highlighted at all.
Set `legacy` option to `true` to bring back old (Jasmine 2.5) output and reporter highlights as well.

- [Release note](https://github.com/mradionov/karma-jasmine-diff-reporter/releases/tag/v1.1.0)
- [Legacy option in README](https://github.com/mradionov/karma-jasmine-diff-reporter#legacy)

Notifying you guys because you voted for the issue: @kiewic @tomonari-t

**Comment by jbarrus** [comment]
I'm getting duplicate output with these settings, is that expected? Is that what you mean by "bring back old output and reporter highlights as well"? If so, any chance this can be changed to show only the diff reported output?

```javascript
PhantomJS 2.1.1 (Mac OS X 0.0.0) document-service-spec getDocuments should retrieve properties and transform to metadata object if the source system supports it FAILED
        Expected undefined to equal <jasmine.objectContaining(Object({ metadata: undefined }))>.
        http://localhost:9878webpack:///test/js/components/document-service-spec.ts:172:35 <- test/index.ts:5525:41
        Expected undefined to equal <jasmine.objectContaining(Object({ metadata: undefined }))>.
        http://localhost:9878webpack:///test/js/components/document-service-spec.ts:173:35 <- test/index.ts:5526:41
        Expected undefined to equal <jasmine.objectContaining(Object({ metadata: Object({ test: [ 123 ] }) }))>.
        http://localhost:9878webpack:///test/js/components/document-service-spec.ts:174:35 <- test/index.ts:5527:41
        Expected undefined to equal <jasmine.objectContaining(Object({ metadata: Object({ test: [ 123 ] }) }))>.
PhantomJS 2.1.1 (Mac OS X 0.0.0) document-service-spec getDocuments should retrieve properties and transform to metadata object if the source system supports it FAILED
        Expected undefined to equal { metadata: undefined }.
        http://localhost:9878webpack:///test/js/components/document-service-spec.ts:172:35 <- test/index.ts:5525:41
        Expected undefined to equal { metadata: undefined }.
        http://localhost:9878webpack:///test/js/components/document-service-spec.ts:173:35 <- test/index.ts:5526:41
        Expected undefined to equal { metadata: Object({ test: [ 123 ] }) }.
        http://localhost:9878webpack:///test/js/components/document-service-spec.ts:174:35 <- test/index.ts:5527:41
        Expected undefined to equal { metadata: Object({ test: [ 123 ] }) }.
        http://localhost:9878webpack:///test/js/components/document-service-spec.ts:175:35 <- test/index.ts:5528:41

```

**Comment by mradionov** [comment]
No, it's not expected. I'll take a look.

**Comment by mradionov** [comment]
@jbarrus I've created a separate issue for this, could you please share with me your configuration files for karma and probably webpack in that [issue](https://github.com/mradionov/karma-jasmine-diff-reporter/issues/30), so I could reproduce it?
