### ISSUE TITLE
Duplicate output with `legacy` option on.

### ISSUE THREAD

**Issue by mradionov** [mradionov/karma-jasmine-diff-reporter#30]
Moved from comment: https://github.com/mradionov/karma-jasmine-diff-reporter/issues/27#issuecomment-334285115

> I'm getting duplicate output with these settings, is that expected? Is that what you mean by "bring back old output and reporter highlights as well"? If so, any chance this can be changed to show only the diff reported output?

![image](https://user-images.githubusercontent.com/2007370/31245561-6b1190a6-aa13-11e7-919b-ff776dd374cf.png)

**Comment by jbarrus** [comment]
I think this might be related to coverage-istanbul, but not sure:

The following result in duplicate output:
['coverage-istanbul', 'progress']
['jasmine-diff', 'coverage-istanbul', 'progress']

The following results in no duplicate output:
['jasmine-diff', 'coverage-istanbul']
['jasmine-diff', 'progress']

I can't seem to give the combination of jasmine-diff, coverage-istanbul and progress to all work together.

**Comment by mradionov** [comment]
I've tried the combination of "coverage-instanbul" and "progress" reporters and it gives me double output as well. Not sure if I can help you with that.
