### ISSUE TITLE
TypeError: value.and.identity is not a function

### ISSUE THREAD

**Issue by azachar** [mradionov/karma-jasmine-diff-reporter#33]
Hello, 
i am getting this very strange error:
	
`TypeError: value.and.identity is not a function in node_modules/karma-jasmine-diff-reporter/src/karma-jasmine/pp-patch.js (line 82)`

I am using these karma dependencies:

```
    "karma": "2.0.0",
    "karma-angular-filesort": "1.0.2",
    "karma-chrome-launcher": "2.2.0",
    "karma-coverage": "1.1.1",
    "karma-firefox-launcher": "1.1.0",
    "karma-jasmine": "1.1.1",
    "karma-jasmine-diff-reporter": "1.1.1",
    "karma-jasmine-matchers": "3.7.0",
    "karma-junit-reporter": "1.2.0",
    "karma-ng-html2js-preprocessor": "1.0.0",
    "karma-ng-pug2js-preprocessor": "1.0.0-beta.0",
    "karma-safari-launcher": "1.0.0",
    "karma-spec-reporter": "0.0.31",
```

Could you please advice what is wrong?

Thank you!

Andrej

**Comment by mradionov** [comment]
Hi, could you please also provide your karma config and a test which is failing?

**Comment by azachar** [comment]
Dear @mradionov, thank you for your super fast response. Sure, but the code is not public, is there a way how to contact you in private? Thx.

**Comment by mradionov** [comment]
Check my email on my profile page

**Comment by azachar** [comment]
done :)

**Comment by mradionov** [comment]
Feel free to reopen if you have more details for me.

**Comment by mradionov** [comment]
New version [1.2.1](https://github.com/mradionov/karma-jasmine-diff-reporter/releases/tag/v1.2.1) with a fix is released and available on [npm](https://www.npmjs.com/package/karma-jasmine-diff-reporter).

**Comment by azachar** [comment]
Thank you for your help @mradionov !
