### ISSUE TITLE
Security vulnerabilities in dependencies reported by npm audit

### ISSUE THREAD

**Issue by ruibasecone** [mradionov/karma-jasmine-diff-reporter#34]
npm audit is reporting security vulnerabilities in some of karma-jasmine-diff-reporter direct or indirect dependencies, so you might consider addressing this.

Affected dependencies:

hoek
timespan
tunnel-agent

**Comment by mradionov** [comment]
All these dependencies are karma dependencies and my reporter is a plugin for karma, there is no way I can drop karma from dependencies or switch it for something else.

Hopefully they will fix their deps soon

https://github.com/karma-runner/karma/issues/2994
https://github.com/karma-runner/karma/pull/2996

**Comment by ruibasecone** [comment]
Right, appreciate the quick reply 👍

**Comment by mradionov** [comment]
https://github.com/karma-runner/karma/issues/2994

In karma 3.0.0 all vulnerable dependencies have been fixed. As a result karma-jasmine-diff-reporter has 0 vulnerabilities now as a result of runing `npm audit` with the latest dependencies.
