### ISSUE TITLE
Pretty print

### ISSUE THREAD

**Issue by mradionov** [mradionov/karma-jasmine-diff-reporter#4]
Implement pretty print option, as it was suggested here: http://stackoverflow.com/a/32280598/1573638

* option in reporter configuration to turn on/off pretty print
```
jasmineDiff: {
    pretty: true
    pretty: false (default)
    pretty: function (objString) {
        return JSON.stringify(objString, null, 4);
    }
}
```
* option to turn on/off pretty print for particular matchers (and custom matchers), because in case of `toThrow` and `toThrowError` pretty print is useless.

* use only for objects (arrays)

**Comment by nkbt** [comment]
See https://github.com/chenglou/react-motion/pull/194

I can so PR here I guess.

**Comment by mradionov** [comment]
I've recently started looking at this issue and the main problem is that I don't have access to Jasmine instance from within the reporter, so I won't be able to replace default matchers or somehow access Jasmine code to easily modify the output. Everything is done through karma and it's reporters mechanism. I'll get deeper into this, but currently the reporter just parses Jasmine failure messages, extracts unequal objects and highlights them. Going with that implementation one should parse a failure message for Object/Array appearance considering multiple level of nesting. I am on investigation stage right now of how to complete this feature, any ideas are welcome. Thanks!

**Comment by nkbt** [comment]
@mradionov you can *JSON.parse* the resulting message actual/expected and then apply pretty-print + diff (in the same way I've done.

JSON in the message might be broken, so it is possible you need to tidy it up somehow or use different json parser (sort of fuzzy-error-tolerant-parser)

**Comment by mradionov** [comment]
@nkbt , just an update that I was able to find a workaround,  pretty print option is in master branch now. I am going to update the docs and do some more tests before publishing though, it is a matter of 1-2 days (if everything goes ok). It would be nice if you could test a version from master with your code, maybe you would also have some suggestions to improve this feature.

```
// karma.conf.js
// ...
  
    jasmineDiffReporter: {
      // if true - 2 spaces for one level of indentation
      // if number - number of spaces for one level of indentation
      // if string - string itself for one level of indentation
      pretty: true  
    }

// ...
```

Thanks! Will notify when it will be published.

**Comment by nkbt** [comment]
Great news! I'll have a look today and let you know asap

**Comment by mradionov** [comment]
@nkbt , everything seems to be ok, I've pushed a new version (0.3.0) to [npm](https://www.npmjs.com/package/karma-jasmine-diff-reporter). Thanks!

**Comment by nkbt** [comment]
Awesome.
