### ISSUE TITLE
Newlines break string highlighting

### ISSUE THREAD

**Issue by skorlir** [mradionov/karma-jasmine-diff-reporter#6]
See:

![String with Newline Breaks Highlighting](http://i.imgur.com/v84JMX8.png)

The first test, in which the compared strings have no newlines, highlights correctly.

The two additional failing tests, although they _are_ failing because string comparison failed, don't highlight.

**Comment by skorlir** [comment]
Oh, although the image doesn't show it, this also happens when both sides are strings - ie, when the left hand side isn't undefined. I just broke my tests before screencapping this :P

**Comment by mradionov** [comment]
Thanks! I am able to reproduce the issue, on my way to fix it.
At the moment all new lines are ignored when comparing data, I guess I'm gonna make them significant.
Just a note for myself that it is not a regression because of the latest pretty print feature from 0.3.0 release.

**Comment by mradionov** [comment]
@skorlir 
Fix is available in a new 0.3.1 version on npm. Thanks for report!

**Comment by skorlir** [comment]
Awesome. Thanks for the quick fix! I'll update my package.json now. :smile:
