### ISSUE TITLE
Additional characters appearing in diff output for string data

### ISSUE THREAD

**Issue by iandarlingmnetics** [mradionov/karma-jasmine-diff-reporter#9]
I'm getting additional characters (a "ÔÇî" sequence) appearing in the output when displaying string data, both in our test suite and the demo one provided.

Environment:
Windows 7 (64 bit)
Node.js 4.2.3 LTS
Karma 0.13.19
Karma-Jasmine: 0.3.7

The attached output is from powershell hosted in the "cmder" utility, although similar results occur in cmd.exe (with "?" appearing instead).

[output.txt](https://github.com/mradionov/karma-jasmine-diff-reporter/files/112695/output.txt)

When running in a normal Powershell window or Git Bash the additional characters do not display or appear in the output.

I'll do some more digging to see if I can isolate the issue.

**Comment by iandarlingmnetics** [comment]
The characters aren't output when karmas "colors" option is set to false

**Comment by mradionov** [comment]
Thanks for the report, I'll try to reproduce the issue and get back to you as soon as I can. Quick guess is that terminals you use do not support character sequences to provide additional styles to the output. By the way, do _karma_ default colored reports work fine or is it just a _karma-jasmine-diff-reporter_ issue?

**Comment by iandarlingmnetics** [comment]
Hi,

I've had a chance to do more digging - for some reason the issue has stopped occuring in my test suite, although it's still reproducable in the demo, so I'm playing with that.

It appears that the dodgy string data is coming into the hooked version of specFailure, if that helps (which suggests it's not your module, at any rate).

In addition, it looks like regular powershell does exhibit the same issue - it's just hard to spot as it renders a thin line (zero width character?) instead of whitespace or ? symbols

**Comment by iandarlingmnetics** [comment]
Also, regular karma colour output is fine.

**Comment by mradionov** [comment]
![image](https://cloud.githubusercontent.com/assets/2007370/12792604/b47289e4-cabd-11e5-924f-2ff013f548d0.png)

I was able to make it running on windows, and I guess you are talking about symbols around strings, correct? You can see extra symbols around strings "foo" and "bar".

**Comment by mradionov** [comment]
Ok, I believe I was able to [fix](https://github.com/mradionov/karma-jasmine-diff-reporter/commit/fd180a1e81b614c420e8a74abb25083e18247ba1) the issue.
New version [0.3.4](https://www.npmjs.com/package/karma-jasmine-diff-reporter) is now available on npm.
Feel free to reopen if it does not work for you after update. Thanks!

**Comment by iandarlingmnetics** [comment]
Yup that looks like my issue - I'll try it out, and thank you for looking at it.

**Comment by iandarlingmnetics** [comment]
I've retested both the repo and my test suite, everything looks great.

**Comment by mradionov** [comment]
Sounds great, thank you for the feedback.
